<config>
    <resolveTypedefs>true</resolveTypedefs>
    <qtMode>true</qtMode>
    <generator>smoke</generator>
    <definesList>@QTDEFINES_FILE@</definesList>
    <includeDirs>
        <dir>@QT_INCLUDE_DIR@</dir>
        <dir>@QT_QTCORE_INCLUDE_DIR@</dir>
        <dir>@QT_QTWEBKIT_INCLUDE_DIR@</dir>
    </includeDirs>
</config>
