#include <kabstractfilewidget.h>
#include <kdiroperator.h>
#include <kdirselectdialog.h>
#include <kdirsortfilterproxymodel.h>
#include <kfilefiltercombo.h>
#include <kfileplacesmodel.h>
#include <kfileplacesview.h>
#include <kfilepreviewgenerator.h>
#include <kfiletreeview.h>
#include <kfilewidget.h>
#include <kurlnavigator.h>
#include <kfile_export.h>
