<config>
    <resolveTypedefs>true</resolveTypedefs>
    <qtMode>true</qtMode>
    <generator>smoke</generator>
    <definesList>@QTDEFINES_FILE@</definesList>
    <includeDirs>
        <dir>@QT_INCLUDE_DIR@</dir>
        <dir>@QT_QTCORE_INCLUDE_DIR@</dir>
        <dir>@QT_QTGUI_INCLUDE_DIR@</dir>
        <dir>@QT_QTNETWORK_INCLUDE_DIR@</dir>
        <dir>@QT_QTDBUS_INCLUDE_DIR@</dir>
        <dir>@QT_QTSQL_INCLUDE_DIR@</dir>
        <dir>@QT_QTXML_INCLUDE_DIR@</dir>
        <dir>@QT_QTOPENGL_INCLUDE_DIR@</dir>
        <dir>@QT_QTSVG_INCLUDE_DIR@</dir>
        <dir>@KDE4_INCLUDE_DIR@</dir>
    </includeDirs>
    <dropMacros>
        <name>__KDE_HAVE_GCC_VISIBILITY</name>
    </dropMacros>
</config>
