//Auto-generated by kalyptus. DO NOT EDIT.
#include <smoke.h>
#include <qt_smoke.h>
#include <qdragobject.h>

class x_QDragManager {
private:
    QDragManager *xthis;
public:
    x_QDragManager(void *x) : xthis((QDragManager*)x) {}
    ~x_QDragManager() {}
};
void xcall_QDragManager(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QDragManager xtmp(obj), *xself = &xtmp;
    switch(xi) {
    }
}
