//Auto-generated by kalyptus. DO NOT EDIT.
#include <smoke.h>
#include <qt_smoke.h>
#include <qvariant.h>
#include <qsizepolicy.h>
#include <qlayout.h>
#include <qrect.h>
#include <qsize.h>

class x_QGridLayout : public QGridLayout {
public:
    static void x_0(Smoke::Stack x) {
	x[0].s_enum = (long)QGridLayout::TopLeft;
    }
    static void x_1(Smoke::Stack x) {
	x[0].s_enum = (long)QGridLayout::TopRight;
    }
    static void x_2(Smoke::Stack x) {
	x[0].s_enum = (long)QGridLayout::BottomLeft;
    }
    static void x_3(Smoke::Stack x) {
	x[0].s_enum = (long)QGridLayout::BottomRight;
    }
    static void x_4(Smoke::Stack x) {
	// QGridLayout(QWidget*, int, int, int, int, const char*)
	x_QGridLayout* xret = new x_QGridLayout((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int,(const char*)x[6].s_voidp);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QWidget* x1, int x2, int x3, int x4, int x5, const char* x6) : QGridLayout(x1, x2, x3, x4, x5, x6) {
    }
    static void x_5(Smoke::Stack x) {
	// QGridLayout(QWidget*, int, int, int, int)
	x_QGridLayout* xret = new x_QGridLayout((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QWidget* x1, int x2, int x3, int x4, int x5) : QGridLayout(x1, x2, x3, x4, x5) {
    }
    static void x_6(Smoke::Stack x) {
	// QGridLayout(QWidget*, int, int, int)
	x_QGridLayout* xret = new x_QGridLayout((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QWidget* x1, int x2, int x3, int x4) : QGridLayout(x1, x2, x3, x4) {
    }
    static void x_7(Smoke::Stack x) {
	// QGridLayout(QWidget*, int, int)
	x_QGridLayout* xret = new x_QGridLayout((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QWidget* x1, int x2, int x3) : QGridLayout(x1, x2, x3) {
    }
    static void x_8(Smoke::Stack x) {
	// QGridLayout(QWidget*, int)
	x_QGridLayout* xret = new x_QGridLayout((QWidget*)x[1].s_class,(int)x[2].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QWidget* x1, int x2) : QGridLayout(x1, x2) {
    }
    static void x_9(Smoke::Stack x) {
	// QGridLayout(QWidget*)
	x_QGridLayout* xret = new x_QGridLayout((QWidget*)x[1].s_class);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QWidget* x1) : QGridLayout(x1) {
    }
    static void x_10(Smoke::Stack x) {
	// QGridLayout(int, int, int, const char*)
	x_QGridLayout* xret = new x_QGridLayout((int)x[1].s_int,(int)x[2].s_int,(int)x[3].s_int,(const char*)x[4].s_voidp);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(int x1, int x2, int x3, const char* x4) : QGridLayout(x1, x2, x3, x4) {
    }
    static void x_11(Smoke::Stack x) {
	// QGridLayout(int, int, int)
	x_QGridLayout* xret = new x_QGridLayout((int)x[1].s_int,(int)x[2].s_int,(int)x[3].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(int x1, int x2, int x3) : QGridLayout(x1, x2, x3) {
    }
    static void x_12(Smoke::Stack x) {
	// QGridLayout(int, int)
	x_QGridLayout* xret = new x_QGridLayout((int)x[1].s_int,(int)x[2].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(int x1, int x2) : QGridLayout(x1, x2) {
    }
    static void x_13(Smoke::Stack x) {
	// QGridLayout(int)
	x_QGridLayout* xret = new x_QGridLayout((int)x[1].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(int x1) : QGridLayout(x1) {
    }
    static void x_14(Smoke::Stack x) {
	// QGridLayout()
	x_QGridLayout* xret = new x_QGridLayout();
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout() : QGridLayout() {
    }
    static void x_15(Smoke::Stack x) {
	// QGridLayout(QLayout*, int, int, int, const char*)
	x_QGridLayout* xret = new x_QGridLayout((QLayout*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(const char*)x[5].s_voidp);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QLayout* x1, int x2, int x3, int x4, const char* x5) : QGridLayout(x1, x2, x3, x4, x5) {
    }
    static void x_16(Smoke::Stack x) {
	// QGridLayout(QLayout*, int, int, int)
	x_QGridLayout* xret = new x_QGridLayout((QLayout*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QLayout* x1, int x2, int x3, int x4) : QGridLayout(x1, x2, x3, x4) {
    }
    static void x_17(Smoke::Stack x) {
	// QGridLayout(QLayout*, int, int)
	x_QGridLayout* xret = new x_QGridLayout((QLayout*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QLayout* x1, int x2, int x3) : QGridLayout(x1, x2, x3) {
    }
    static void x_18(Smoke::Stack x) {
	// QGridLayout(QLayout*, int)
	x_QGridLayout* xret = new x_QGridLayout((QLayout*)x[1].s_class,(int)x[2].s_int);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QLayout* x1, int x2) : QGridLayout(x1, x2) {
    }
    static void x_19(Smoke::Stack x) {
	// QGridLayout(QLayout*)
	x_QGridLayout* xret = new x_QGridLayout((QLayout*)x[1].s_class);
	x[0].s_class = (void*)xret;
    }
    x_QGridLayout(QLayout* x1) : QGridLayout(x1) {
    }
    void x_20(Smoke::Stack x) const {
	// sizeHint()
	QSize xret = this->QGridLayout::sizeHint();
	x[0].s_class = (void*)new QSize(xret);
    }
    void x_21(Smoke::Stack x) const {
	// minimumSize()
	QSize xret = this->QGridLayout::minimumSize();
	x[0].s_class = (void*)new QSize(xret);
    }
    void x_22(Smoke::Stack x) const {
	// maximumSize()
	QSize xret = this->QGridLayout::maximumSize();
	x[0].s_class = (void*)new QSize(xret);
    }
    void x_23(Smoke::Stack x) {
	// setRowStretch(int, int)
	this->QGridLayout::setRowStretch((int)x[1].s_int,(int)x[2].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_24(Smoke::Stack x) {
	// setColStretch(int, int)
	this->QGridLayout::setColStretch((int)x[1].s_int,(int)x[2].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_25(Smoke::Stack x) const {
	// rowStretch(int)
	int xret = this->QGridLayout::rowStretch((int)x[1].s_int);
	x[0].s_int = xret;
    }
    void x_26(Smoke::Stack x) const {
	// colStretch(int)
	int xret = this->QGridLayout::colStretch((int)x[1].s_int);
	x[0].s_int = xret;
    }
    void x_27(Smoke::Stack x) const {
	// numRows()
	int xret = this->QGridLayout::numRows();
	x[0].s_int = xret;
    }
    void x_28(Smoke::Stack x) const {
	// numCols()
	int xret = this->QGridLayout::numCols();
	x[0].s_int = xret;
    }
    void x_29(Smoke::Stack x) const {
	// cellGeometry(int, int)
	QRect xret = this->QGridLayout::cellGeometry((int)x[1].s_int,(int)x[2].s_int);
	x[0].s_class = (void*)new QRect(xret);
    }
    void x_30(Smoke::Stack x) const {
	// hasHeightForWidth()
	bool xret = this->QGridLayout::hasHeightForWidth();
	x[0].s_bool = xret;
    }
    void x_31(Smoke::Stack x) const {
	// heightForWidth(int)
	int xret = this->QGridLayout::heightForWidth((int)x[1].s_int);
	x[0].s_int = xret;
    }
    void x_32(Smoke::Stack x) const {
	// expanding()
	QSizePolicy::ExpandData xret = this->QGridLayout::expanding();
	x[0].s_enum = xret;
    }
    void x_33(Smoke::Stack x) {
	// invalidate()
	this->QGridLayout::invalidate();
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_34(Smoke::Stack x) {
	// addItem(QLayoutItem*)
	this->QGridLayout::addItem((QLayoutItem*)x[1].s_class);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_35(Smoke::Stack x) {
	// addItem(QLayoutItem*, int, int)
	this->QGridLayout::addItem((QLayoutItem*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_36(Smoke::Stack x) {
	// addMultiCell(QLayoutItem*, int, int, int, int, int)
	this->QGridLayout::addMultiCell((QLayoutItem*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int,(int)x[6].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_37(Smoke::Stack x) {
	// addMultiCell(QLayoutItem*, int, int, int, int)
	this->QGridLayout::addMultiCell((QLayoutItem*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_38(Smoke::Stack x) {
	// addWidget(QWidget*, int, int, int)
	this->QGridLayout::addWidget((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_39(Smoke::Stack x) {
	// addWidget(QWidget*, int, int)
	this->QGridLayout::addWidget((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_40(Smoke::Stack x) {
	// addMultiCellWidget(QWidget*, int, int, int, int, int)
	this->QGridLayout::addMultiCellWidget((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int,(int)x[6].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_41(Smoke::Stack x) {
	// addMultiCellWidget(QWidget*, int, int, int, int)
	this->QGridLayout::addMultiCellWidget((QWidget*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_42(Smoke::Stack x) {
	// addLayout(QLayout*, int, int)
	this->QGridLayout::addLayout((QLayout*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_43(Smoke::Stack x) {
	// addMultiCellLayout(QLayout*, int, int, int, int, int)
	this->QGridLayout::addMultiCellLayout((QLayout*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int,(int)x[6].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_44(Smoke::Stack x) {
	// addMultiCellLayout(QLayout*, int, int, int, int)
	this->QGridLayout::addMultiCellLayout((QLayout*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int,(int)x[4].s_int,(int)x[5].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_45(Smoke::Stack x) {
	// addRowSpacing(int, int)
	this->QGridLayout::addRowSpacing((int)x[1].s_int,(int)x[2].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_46(Smoke::Stack x) {
	// addColSpacing(int, int)
	this->QGridLayout::addColSpacing((int)x[1].s_int,(int)x[2].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_47(Smoke::Stack x) {
	// expand(int, int)
	this->QGridLayout::expand((int)x[1].s_int,(int)x[2].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_48(Smoke::Stack x) {
	// setOrigin(QGridLayout::Corner)
	this->QGridLayout::setOrigin((QGridLayout::Corner)x[1].s_enum);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_49(Smoke::Stack x) const {
	// origin()
	QGridLayout::Corner xret = this->QGridLayout::origin();
	x[0].s_enum = xret;
    }
    void x_50(Smoke::Stack x) {
	// iterator()
	QLayoutIterator xret = this->QGridLayout::iterator();
	x[0].s_class = (void*)new QLayoutIterator(xret);
    }
    void x_51(Smoke::Stack x) {
	// setGeometry(const QRect&)
	this->QGridLayout::setGeometry(*(const QRect *)x[1].s_class);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    void x_52(Smoke::Stack x) {
	// findWidget(QWidget*, int*, int*)
	bool xret = this->QGridLayout::findWidget((QWidget*)x[1].s_class,(int*)x[2].s_voidp,(int*)x[3].s_voidp);
	x[0].s_bool = xret;
    }
    void x_53(Smoke::Stack x) {
	// add(QLayoutItem*, int, int)
	this->QGridLayout::add((QLayoutItem*)x[1].s_class,(int)x[2].s_int,(int)x[3].s_int);
	(void)x[0].s_int; // noop (for compiler warning)
    }
    virtual void addItem(QLayoutItem* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(3128, (void*)this, x)) return;
	this->QGridLayout::addItem(x1);
    }
    virtual bool checkConnectArgs(const char* x1, const QObject* x2, const char* x3) {
	Smoke::StackItem x[4];
	x[1].s_voidp = (void*)x1;
	x[2].s_class = (void*)x2;
	x[3].s_voidp = (void*)x3;
	if(qt_Smoke->binding->callMethod(5470, (void*)this, x)) return (bool)x[0].s_bool;
	return this->QObject::checkConnectArgs(x1, x2, x3);
    }
    virtual void childEvent(QChildEvent* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(4101, (void*)this, x)) return;
	this->QLayout::childEvent(x1);
    }
    virtual void connectNotify(const char* x1) {
	Smoke::StackItem x[2];
	x[1].s_voidp = (void*)x1;
	if(qt_Smoke->binding->callMethod(5468, (void*)this, x)) return;
	this->QObject::connectNotify(x1);
    }
    virtual void customEvent(QCustomEvent* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(5467, (void*)this, x)) return;
	this->QObject::customEvent(x1);
    }
    virtual void disconnectNotify(const char* x1) {
	Smoke::StackItem x[2];
	x[1].s_voidp = (void*)x1;
	if(qt_Smoke->binding->callMethod(5469, (void*)this, x)) return;
	this->QObject::disconnectNotify(x1);
    }
    virtual bool event(QEvent* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(5405, (void*)this, x)) return (bool)x[0].s_bool;
	return this->QObject::event(x1);
    }
    virtual bool eventFilter(QObject* x1, QEvent* x2) {
	Smoke::StackItem x[3];
	x[1].s_class = (void*)x1;
	x[2].s_class = (void*)x2;
	if(qt_Smoke->binding->callMethod(4100, (void*)this, x)) return (bool)x[0].s_bool;
	return this->QLayout::eventFilter(x1, x2);
    }
    virtual QSizePolicy::ExpandData expanding() const {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(3126, (void*)this, x)) {
	    QSizePolicy::ExpandData *xptr = (QSizePolicy::ExpandData *)x[0].s_class;
	    QSizePolicy::ExpandData xret(*xptr);
	    delete xptr;
	    return xret;
	}
	return this->QGridLayout::expanding();
    }
    virtual QRect geometry() const {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(4082, (void*)this, x)) {
	    QRect *xptr = (QRect *)x[0].s_class;
	    QRect xret(*xptr);
	    delete xptr;
	    return xret;
	}
	return this->QLayout::geometry();
    }
    virtual bool hasHeightForWidth() const {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(3124, (void*)this, x)) return (bool)x[0].s_bool;
	return this->QGridLayout::hasHeightForWidth();
    }
    virtual int heightForWidth(int x1) const {
	Smoke::StackItem x[2];
	x[1].s_int = x1;
	if(qt_Smoke->binding->callMethod(3125, (void*)this, x)) return (int)x[0].s_int;
	return this->QGridLayout::heightForWidth(x1);
    }
    virtual void insertChild(QObject* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(5428, (void*)this, x)) return;
	this->QObject::insertChild(x1);
    }
    virtual void invalidate() {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(3127, (void*)this, x)) return;
	this->QGridLayout::invalidate();
    }
    virtual bool isEmpty() const {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(4091, (void*)this, x)) return (bool)x[0].s_bool;
	return this->QLayout::isEmpty();
    }
    virtual QLayoutIterator iterator() {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(3144, (void*)this, x)) {
	    QLayoutIterator *xptr = (QLayoutIterator *)x[0].s_class;
	    QLayoutIterator xret(*xptr);
	    delete xptr;
	    return xret;
	}
	return this->QGridLayout::iterator();
    }
    virtual QLayout* layout() {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(4096, (void*)this, x)) return (QLayout*)x[0].s_class;
	return this->QLayout::layout();
    }
    virtual QSize maximumSize() const {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(3116, (void*)this, x)) {
	    QSize *xptr = (QSize *)x[0].s_class;
	    QSize xret(*xptr);
	    delete xptr;
	    return xret;
	}
	return this->QGridLayout::maximumSize();
    }
    virtual QSize minimumSize() const {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(3115, (void*)this, x)) {
	    QSize *xptr = (QSize *)x[0].s_class;
	    QSize xret(*xptr);
	    delete xptr;
	    return xret;
	}
	return this->QGridLayout::minimumSize();
    }
    virtual QVariant property(const char* x1) const {
	Smoke::StackItem x[2];
	x[1].s_voidp = (void*)x1;
	if(qt_Smoke->binding->callMethod(5442, (void*)this, x)) {
	    QVariant *xptr = (QVariant *)x[0].s_class;
	    QVariant xret(*xptr);
	    delete xptr;
	    return xret;
	}
	return this->QObject::property(x1);
    }
    virtual void removeChild(QObject* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(5429, (void*)this, x)) return;
	this->QObject::removeChild(x1);
    }
    virtual void setAlignment(int x1) {
	Smoke::StackItem x[2];
	x[1].s_int = x1;
	if(qt_Smoke->binding->callMethod(4124, (void*)this, x)) return;
	this->QLayoutItem::setAlignment(x1);
    }
    virtual void setAutoAdd(bool x1) {
	Smoke::StackItem x[2];
	x[1].s_bool = x1;
	if(qt_Smoke->binding->callMethod(4079, (void*)this, x)) return;
	this->QLayout::setAutoAdd(x1);
    }
    virtual void setColStretch(int x1, int x2) {
	Smoke::StackItem x[3];
	x[1].s_int = x1;
	x[2].s_int = x2;
	if(qt_Smoke->binding->callMethod(3118, (void*)this, x)) return;
	this->QGridLayout::setColStretch(x1, x2);
    }
    virtual void setGeometry(const QRect& x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)&x1;
	if(qt_Smoke->binding->callMethod(3145, (void*)this, x)) return;
	this->QGridLayout::setGeometry(x1);
    }
    virtual void setMargin(int x1) {
	Smoke::StackItem x[2];
	x[1].s_int = x1;
	if(qt_Smoke->binding->callMethod(4068, (void*)this, x)) return;
	this->QLayout::setMargin(x1);
    }
    virtual void setMenuBar(QMenuBar* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(4075, (void*)this, x)) return;
	this->QLayout::setMenuBar(x1);
    }
    virtual void setName(const char* x1) {
	Smoke::StackItem x[2];
	x[1].s_voidp = (void*)x1;
	if(qt_Smoke->binding->callMethod(5411, (void*)this, x)) return;
	this->QObject::setName(x1);
    }
    virtual bool setProperty(const char* x1, const QVariant& x2) {
	Smoke::StackItem x[3];
	x[1].s_voidp = (void*)x1;
	x[2].s_class = (void*)&x2;
	if(qt_Smoke->binding->callMethod(5441, (void*)this, x)) return (bool)x[0].s_bool;
	return this->QObject::setProperty(x1, x2);
    }
    virtual void setRowStretch(int x1, int x2) {
	Smoke::StackItem x[3];
	x[1].s_int = x1;
	x[2].s_int = x2;
	if(qt_Smoke->binding->callMethod(3117, (void*)this, x)) return;
	this->QGridLayout::setRowStretch(x1, x2);
    }
    virtual void setSpacing(int x1) {
	Smoke::StackItem x[2];
	x[1].s_int = x1;
	if(qt_Smoke->binding->callMethod(4069, (void*)this, x)) return;
	this->QLayout::setSpacing(x1);
    }
    virtual QSize sizeHint() const {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(3114, (void*)this, x)) {
	    QSize *xptr = (QSize *)x[0].s_class;
	    QSize xret(*xptr);
	    delete xptr;
	    return xret;
	}
	return this->QGridLayout::sizeHint();
    }
    virtual QSpacerItem* spacerItem() {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(4122, (void*)this, x)) return (QSpacerItem*)x[0].s_class;
	return this->QLayoutItem::spacerItem();
    }
    virtual void timerEvent(QTimerEvent* x1) {
	Smoke::StackItem x[2];
	x[1].s_class = (void*)x1;
	if(qt_Smoke->binding->callMethod(5465, (void*)this, x)) return;
	this->QObject::timerEvent(x1);
    }
    virtual QWidget* widget() {
	Smoke::StackItem x[1];
	if(qt_Smoke->binding->callMethod(4119, (void*)this, x)) return (QWidget*)x[0].s_class;
	return this->QLayoutItem::widget();
    }
    ~x_QGridLayout() { qt_Smoke->binding->deleted(133, (void*)this); }
};
void xcall_QGridLayout(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QGridLayout *xself = (x_QGridLayout*)obj;
    switch(xi) {
	case 0: x_QGridLayout::x_0(args);	break;
	case 1: x_QGridLayout::x_1(args);	break;
	case 2: x_QGridLayout::x_2(args);	break;
	case 3: x_QGridLayout::x_3(args);	break;
	case 4: x_QGridLayout::x_4(args);	break;
	case 5: x_QGridLayout::x_5(args);	break;
	case 6: x_QGridLayout::x_6(args);	break;
	case 7: x_QGridLayout::x_7(args);	break;
	case 8: x_QGridLayout::x_8(args);	break;
	case 9: x_QGridLayout::x_9(args);	break;
	case 10: x_QGridLayout::x_10(args);	break;
	case 11: x_QGridLayout::x_11(args);	break;
	case 12: x_QGridLayout::x_12(args);	break;
	case 13: x_QGridLayout::x_13(args);	break;
	case 14: x_QGridLayout::x_14(args);	break;
	case 15: x_QGridLayout::x_15(args);	break;
	case 16: x_QGridLayout::x_16(args);	break;
	case 17: x_QGridLayout::x_17(args);	break;
	case 18: x_QGridLayout::x_18(args);	break;
	case 19: x_QGridLayout::x_19(args);	break;
	case 20: xself->x_20(args);	break;
	case 21: xself->x_21(args);	break;
	case 22: xself->x_22(args);	break;
	case 23: xself->x_23(args);	break;
	case 24: xself->x_24(args);	break;
	case 25: xself->x_25(args);	break;
	case 26: xself->x_26(args);	break;
	case 27: xself->x_27(args);	break;
	case 28: xself->x_28(args);	break;
	case 29: xself->x_29(args);	break;
	case 30: xself->x_30(args);	break;
	case 31: xself->x_31(args);	break;
	case 32: xself->x_32(args);	break;
	case 33: xself->x_33(args);	break;
	case 34: xself->x_34(args);	break;
	case 35: xself->x_35(args);	break;
	case 36: xself->x_36(args);	break;
	case 37: xself->x_37(args);	break;
	case 38: xself->x_38(args);	break;
	case 39: xself->x_39(args);	break;
	case 40: xself->x_40(args);	break;
	case 41: xself->x_41(args);	break;
	case 42: xself->x_42(args);	break;
	case 43: xself->x_43(args);	break;
	case 44: xself->x_44(args);	break;
	case 45: xself->x_45(args);	break;
	case 46: xself->x_46(args);	break;
	case 47: xself->x_47(args);	break;
	case 48: xself->x_48(args);	break;
	case 49: xself->x_49(args);	break;
	case 50: xself->x_50(args);	break;
	case 51: xself->x_51(args);	break;
	case 52: xself->x_52(args);	break;
	case 53: xself->x_53(args);	break;
	case 54: delete (QGridLayout*)xself;	break;
    }
}
