//Auto-generated by kalyptus. DO NOT EDIT.
#include <smoke_types.h>
#include <qasyncimageio.h>
#include <qimage.h>
#include <qstrlist.h>

class x_QImageDecoder : public QImageDecoder {
public:
    static void x_0(xargs *x) {
	// QImageDecoder(QImageConsumer*)
	x_QImageDecoder* xret = new x_QImageDecoder((QImageConsumer*)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QImageDecoder(QImageConsumer* x1) : QImageDecoder(x1) {
    }
    void x_1(xargs *x) {
	// image()
	const QImage& xret = this->QImageDecoder::image();
	x[0].x_voidp = (void*)&xret;
    }
    void x_2(xargs *x) {
	// decode(const uchar*, int)
	int xret = this->QImageDecoder::decode((const uchar*)x[1].x_voidp,(int)x[2].x_int);
	x[0].x_int = (int)xret;
    }
    static void x_3(xargs *x) {
	// formatName(const uchar*, int)
	const char* xret = QImageDecoder::formatName((const uchar*)x[1].x_voidp,(int)x[2].x_int);
	x[0].x_voidp = (void*)xret;
    }
    static void x_4(xargs *x) {
	// format(const char*)
	QImageFormatType* xret = QImageDecoder::format((const char*)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    static void x_5(xargs *x) {
	// inputFormats()
	QStrList xret = QImageDecoder::inputFormats();
	x[0].x_voidp = (void*)new QStrList(xret);
    }
    static void x_6(xargs *x) {
	// registerDecoderFactory(QImageFormatType*)
	QImageDecoder::registerDecoderFactory((QImageFormatType*)x[1].x_voidp);
    }
    static void x_7(xargs *x) {
	// unregisterDecoderFactory(QImageFormatType*)
	QImageDecoder::unregisterDecoderFactory((QImageFormatType*)x[1].x_voidp);
    }
    ~x_QImageDecoder() {}
};
void xcall_QImageDecoder(xargs *x, void *s, int xi) {
    x_QImageDecoder *xself = (x_QImageDecoder*)s;
    switch(xi) {
	case 0: x_QImageDecoder::x_0(x);	break;
	case 1: xself->x_1(x);	break;
	case 2: xself->x_2(x);	break;
	case 3: x_QImageDecoder::x_3(x);	break;
	case 4: x_QImageDecoder::x_4(x);	break;
	case 5: x_QImageDecoder::x_5(x);	break;
	case 6: x_QImageDecoder::x_6(x);	break;
	case 7: x_QImageDecoder::x_7(x);	break;
	case 8: delete (QImageDecoder*)xself;	break;
    }
}
