//Auto-generated by kalyptus. DO NOT EDIT.
#include <smoke_types.h>
#include <qpoint.h>
#include <qimage.h>
#include <qcolor.h>
#include <qcstring.h>
#include <qstring.h>
#include <qbitmap.h>
#include <qsize.h>
#include <qwmatrix.h>
#include <qpixmap.h>
#include <qrect.h>

class x_QPixmap : public QPixmap {
public:
    static void x_0(xargs *x) {
	x[0].x_long = (long)QPixmap::Auto;
    }
    static void x_1(xargs *x) {
	x[0].x_long = (long)QPixmap::Color;
    }
    static void x_2(xargs *x) {
	x[0].x_long = (long)QPixmap::Mono;
    }
    static void x_3(xargs *x) {
	x[0].x_long = (long)QPixmap::DefaultOptim;
    }
    static void x_4(xargs *x) {
	x[0].x_long = (long)QPixmap::NoOptim;
    }
    static void x_5(xargs *x) {
	x[0].x_long = (long)QPixmap::MemoryOptim;
    }
    static void x_6(xargs *x) {
	x[0].x_long = (long)QPixmap::NormalOptim;
    }
    static void x_7(xargs *x) {
	x[0].x_long = (long)QPixmap::BestOptim;
    }
    static void x_8(xargs *x) {
	// QPixmap()
	x_QPixmap* xret = new x_QPixmap();
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap() : QPixmap() {
    }
    static void x_9(xargs *x) {
	// QPixmap(const QImage&)
	x_QPixmap* xret = new x_QPixmap(*(const QImage *)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QImage& x1) : QPixmap(x1) {
    }
    static void x_10(xargs *x) {
	// QPixmap(int, int, int, QPixmap::Optimization)
	x_QPixmap* xret = new x_QPixmap((int)x[1].x_int,(int)x[2].x_int,(int)x[3].x_int,(QPixmap::Optimization)x[4].x_long);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(int x1, int x2, int x3, QPixmap::Optimization x4) : QPixmap(x1, x2, x3, x4) {
    }
    static void x_11(xargs *x) {
	// QPixmap(int, int, int)
	x_QPixmap* xret = new x_QPixmap((int)x[1].x_int,(int)x[2].x_int,(int)x[3].x_int);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(int x1, int x2, int x3) : QPixmap(x1, x2, x3) {
    }
    static void x_12(xargs *x) {
	// QPixmap(int, int)
	x_QPixmap* xret = new x_QPixmap((int)x[1].x_int,(int)x[2].x_int);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(int x1, int x2) : QPixmap(x1, x2) {
    }
    static void x_13(xargs *x) {
	// QPixmap(const QSize&, int, QPixmap::Optimization)
	x_QPixmap* xret = new x_QPixmap(*(const QSize *)x[1].x_voidp,(int)x[2].x_int,(QPixmap::Optimization)x[3].x_long);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QSize& x1, int x2, QPixmap::Optimization x3) : QPixmap(x1, x2, x3) {
    }
    static void x_14(xargs *x) {
	// QPixmap(const QSize&, int)
	x_QPixmap* xret = new x_QPixmap(*(const QSize *)x[1].x_voidp,(int)x[2].x_int);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QSize& x1, int x2) : QPixmap(x1, x2) {
    }
    static void x_15(xargs *x) {
	// QPixmap(const QSize&)
	x_QPixmap* xret = new x_QPixmap(*(const QSize *)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QSize& x1) : QPixmap(x1) {
    }
    static void x_16(xargs *x) {
	// QPixmap(const QString&, const char*, QPixmap::ColorMode)
	x_QPixmap* xret = new x_QPixmap(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp,(QPixmap::ColorMode)x[3].x_long);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QString& x1, const char* x2, QPixmap::ColorMode x3) : QPixmap(x1, x2, x3) {
    }
    static void x_17(xargs *x) {
	// QPixmap(const QString&, const char*)
	x_QPixmap* xret = new x_QPixmap(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QString& x1, const char* x2) : QPixmap(x1, x2) {
    }
    static void x_18(xargs *x) {
	// QPixmap(const QString&)
	x_QPixmap* xret = new x_QPixmap(*(const QString *)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QString& x1) : QPixmap(x1) {
    }
    static void x_19(xargs *x) {
	// QPixmap(const QString&, const char*, int)
	x_QPixmap* xret = new x_QPixmap(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp,(int)x[3].x_int);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QString& x1, const char* x2, int x3) : QPixmap(x1, x2, x3) {
    }
    static void x_20(xargs *x) {
	// QPixmap(const char**)
	x_QPixmap* xret = new x_QPixmap((const char**)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const char** x1) : QPixmap(x1) {
    }
    static void x_21(xargs *x) {
	// QPixmap(const QByteArray&)
	x_QPixmap* xret = new x_QPixmap(*(const QByteArray *)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QByteArray& x1) : QPixmap(x1) {
    }
    static void x_22(xargs *x) {
	// QPixmap(const QPixmap&)
	x_QPixmap* xret = new x_QPixmap(*(const QPixmap *)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(const QPixmap& x1) : QPixmap(x1) {
    }
    void x_23(xargs *x) {
	// operator=(const QPixmap&)
	QPixmap& xret = this->QPixmap::operator=(*(const QPixmap *)x[1].x_voidp);
	x[0].x_voidp = (void*)&xret;
    }
    void x_24(xargs *x) {
	// operator=(const QImage&)
	QPixmap& xret = this->QPixmap::operator=(*(const QImage *)x[1].x_voidp);
	x[0].x_voidp = (void*)&xret;
    }
    void x_25(xargs *x) const {
	// isNull()
	bool xret = this->QPixmap::isNull();
	x[0].x_bool = (bool)xret;
    }
    void x_26(xargs *x) const {
	// width()
	int xret = this->QPixmap::width();
	x[0].x_int = (int)xret;
    }
    void x_27(xargs *x) const {
	// height()
	int xret = this->QPixmap::height();
	x[0].x_int = (int)xret;
    }
    void x_28(xargs *x) const {
	// size()
	QSize xret = this->QPixmap::size();
	x[0].x_voidp = (void*)new QSize(xret);
    }
    void x_29(xargs *x) const {
	// rect()
	QRect xret = this->QPixmap::rect();
	x[0].x_voidp = (void*)new QRect(xret);
    }
    void x_30(xargs *x) const {
	// depth()
	int xret = this->QPixmap::depth();
	x[0].x_int = (int)xret;
    }
    void x_31(xargs *x) {
	// fill(const QColor&)
	this->QPixmap::fill(*(const QColor *)x[1].x_voidp);
    }
    void x_32(xargs *x) {
	// fill()
	this->QPixmap::fill();
    }
    void x_33(xargs *x) {
	// fill(const QWidget*, int, int)
	this->QPixmap::fill((const QWidget*)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int);
    }
    void x_34(xargs *x) {
	// fill(const QWidget*, const QPoint&)
	this->QPixmap::fill((const QWidget*)x[1].x_voidp,*(const QPoint *)x[2].x_voidp);
    }
    void x_35(xargs *x) {
	// resize(int, int)
	this->QPixmap::resize((int)x[1].x_int,(int)x[2].x_int);
    }
    void x_36(xargs *x) {
	// resize(const QSize&)
	this->QPixmap::resize(*(const QSize *)x[1].x_voidp);
    }
    void x_37(xargs *x) const {
	// mask()
	const QBitmap* xret = this->QPixmap::mask();
	x[0].x_voidp = (void*)xret;
    }
    void x_38(xargs *x) {
	// setMask(const QBitmap&)
	this->QPixmap::setMask(*(const QBitmap *)x[1].x_voidp);
    }
    void x_39(xargs *x) const {
	// selfMask()
	bool xret = this->QPixmap::selfMask();
	x[0].x_bool = (bool)xret;
    }
    void x_40(xargs *x) const {
	// createHeuristicMask(bool)
	QBitmap xret = this->QPixmap::createHeuristicMask((bool)x[1].x_bool);
	x[0].x_voidp = (void*)new QBitmap(xret);
    }
    void x_41(xargs *x) const {
	// createHeuristicMask()
	QBitmap xret = this->QPixmap::createHeuristicMask();
	x[0].x_voidp = (void*)new QBitmap(xret);
    }
    void x_42(xargs *x) const {
	// xForm(const QWMatrix&)
	QPixmap xret = this->QPixmap::xForm(*(const QWMatrix *)x[1].x_voidp);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    void x_43(xargs *x) const {
	// convertToImage()
	QImage xret = this->QPixmap::convertToImage();
	x[0].x_voidp = (void*)new QImage(xret);
    }
    void x_44(xargs *x) {
	// convertFromImage(const QImage&, QPixmap::ColorMode)
	bool xret = this->QPixmap::convertFromImage(*(const QImage *)x[1].x_voidp,(QPixmap::ColorMode)x[2].x_long);
	x[0].x_bool = (bool)xret;
    }
    void x_45(xargs *x) {
	// convertFromImage(const QImage&)
	bool xret = this->QPixmap::convertFromImage(*(const QImage *)x[1].x_voidp);
	x[0].x_bool = (bool)xret;
    }
    void x_46(xargs *x) {
	// convertFromImage(const QImage&, int)
	bool xret = this->QPixmap::convertFromImage(*(const QImage *)x[1].x_voidp,(int)x[2].x_int);
	x[0].x_bool = (bool)xret;
    }
    void x_47(xargs *x) {
	// load(const QString&, const char*, QPixmap::ColorMode)
	bool xret = this->QPixmap::load(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp,(QPixmap::ColorMode)x[3].x_long);
	x[0].x_bool = (bool)xret;
    }
    void x_48(xargs *x) {
	// load(const QString&, const char*)
	bool xret = this->QPixmap::load(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp);
	x[0].x_bool = (bool)xret;
    }
    void x_49(xargs *x) {
	// load(const QString&)
	bool xret = this->QPixmap::load(*(const QString *)x[1].x_voidp);
	x[0].x_bool = (bool)xret;
    }
    void x_50(xargs *x) {
	// load(const QString&, const char*, int)
	bool xret = this->QPixmap::load(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp,(int)x[3].x_int);
	x[0].x_bool = (bool)xret;
    }
    void x_51(xargs *x) {
	// loadFromData(const uchar*, uint, const char*, QPixmap::ColorMode)
	bool xret = this->QPixmap::loadFromData((const uchar*)x[1].x_voidp,(uint)x[2].x_uint,(const char*)x[3].x_voidp,(QPixmap::ColorMode)x[4].x_long);
	x[0].x_bool = (bool)xret;
    }
    void x_52(xargs *x) {
	// loadFromData(const uchar*, uint, const char*)
	bool xret = this->QPixmap::loadFromData((const uchar*)x[1].x_voidp,(uint)x[2].x_uint,(const char*)x[3].x_voidp);
	x[0].x_bool = (bool)xret;
    }
    void x_53(xargs *x) {
	// loadFromData(const uchar*, uint)
	bool xret = this->QPixmap::loadFromData((const uchar*)x[1].x_voidp,(uint)x[2].x_uint);
	x[0].x_bool = (bool)xret;
    }
    void x_54(xargs *x) {
	// loadFromData(const uchar*, uint, const char*, int)
	bool xret = this->QPixmap::loadFromData((const uchar*)x[1].x_voidp,(uint)x[2].x_uint,(const char*)x[3].x_voidp,(int)x[4].x_int);
	x[0].x_bool = (bool)xret;
    }
    void x_55(xargs *x) {
	// loadFromData(const QByteArray&, const char*, int)
	bool xret = this->QPixmap::loadFromData(*(const QByteArray *)x[1].x_voidp,(const char*)x[2].x_voidp,(int)x[3].x_int);
	x[0].x_bool = (bool)xret;
    }
    void x_56(xargs *x) {
	// loadFromData(const QByteArray&, const char*)
	bool xret = this->QPixmap::loadFromData(*(const QByteArray *)x[1].x_voidp,(const char*)x[2].x_voidp);
	x[0].x_bool = (bool)xret;
    }
    void x_57(xargs *x) {
	// loadFromData(const QByteArray&)
	bool xret = this->QPixmap::loadFromData(*(const QByteArray *)x[1].x_voidp);
	x[0].x_bool = (bool)xret;
    }
    void x_58(xargs *x) const {
	// save(const QString&, const char*, int)
	bool xret = this->QPixmap::save(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp,(int)x[3].x_int);
	x[0].x_bool = (bool)xret;
    }
    void x_59(xargs *x) const {
	// save(const QString&, const char*)
	bool xret = this->QPixmap::save(*(const QString *)x[1].x_voidp,(const char*)x[2].x_voidp);
	x[0].x_bool = (bool)xret;
    }
    void x_60(xargs *x) const {
	// serialNumber()
	int xret = this->QPixmap::serialNumber();
	x[0].x_int = (int)xret;
    }
    void x_61(xargs *x) const {
	// optimization()
	QPixmap::Optimization xret = this->QPixmap::optimization();
	x[0].x_long = (long)xret;
    }
    void x_62(xargs *x) {
	// setOptimization(QPixmap::Optimization)
	this->QPixmap::setOptimization((QPixmap::Optimization)x[1].x_long);
    }
    void x_63(xargs *x) {
	// detach()
	this->QPixmap::detach();
    }
    void x_64(xargs *x) const {
	// isQBitmap()
	bool xret = this->QPixmap::isQBitmap();
	x[0].x_bool = (bool)xret;
    }
    static void x_65(xargs *x) {
	// defaultDepth()
	int xret = QPixmap::defaultDepth();
	x[0].x_int = (int)xret;
    }
    static void x_66(xargs *x) {
	// grabWindow(WId, int, int, int, int)
	QPixmap xret = QPixmap::grabWindow(*(WId *)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int,(int)x[4].x_int,(int)x[5].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_67(xargs *x) {
	// grabWindow(WId, int, int, int)
	QPixmap xret = QPixmap::grabWindow(*(WId *)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int,(int)x[4].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_68(xargs *x) {
	// grabWindow(WId, int, int)
	QPixmap xret = QPixmap::grabWindow(*(WId *)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_69(xargs *x) {
	// grabWindow(WId, int)
	QPixmap xret = QPixmap::grabWindow(*(WId *)x[1].x_voidp,(int)x[2].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_70(xargs *x) {
	// grabWindow(WId)
	QPixmap xret = QPixmap::grabWindow(*(WId *)x[1].x_voidp);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_71(xargs *x) {
	// grabWidget(QWidget*, int, int, int, int)
	QPixmap xret = QPixmap::grabWidget((QWidget*)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int,(int)x[4].x_int,(int)x[5].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_72(xargs *x) {
	// grabWidget(QWidget*, int, int, int)
	QPixmap xret = QPixmap::grabWidget((QWidget*)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int,(int)x[4].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_73(xargs *x) {
	// grabWidget(QWidget*, int, int)
	QPixmap xret = QPixmap::grabWidget((QWidget*)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_74(xargs *x) {
	// grabWidget(QWidget*, int)
	QPixmap xret = QPixmap::grabWidget((QWidget*)x[1].x_voidp,(int)x[2].x_int);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_75(xargs *x) {
	// grabWidget(QWidget*)
	QPixmap xret = QPixmap::grabWidget((QWidget*)x[1].x_voidp);
	x[0].x_voidp = (void*)new QPixmap(xret);
    }
    static void x_76(xargs *x) {
	// trueMatrix(const QWMatrix&, int, int)
	QWMatrix xret = QPixmap::trueMatrix(*(const QWMatrix *)x[1].x_voidp,(int)x[2].x_int,(int)x[3].x_int);
	x[0].x_voidp = (void*)new QWMatrix(xret);
    }
    static void x_77(xargs *x) {
	// imageFormat(const QString&)
	const char* xret = QPixmap::imageFormat(*(const QString *)x[1].x_voidp);
	x[0].x_voidp = (void*)xret;
    }
    static void x_78(xargs *x) {
	// defaultOptimization()
	QPixmap::Optimization xret = QPixmap::defaultOptimization();
	x[0].x_long = (long)xret;
    }
    static void x_79(xargs *x) {
	// setDefaultOptimization(QPixmap::Optimization)
	QPixmap::setDefaultOptimization((QPixmap::Optimization)x[1].x_long);
    }
    static void x_80(xargs *x) {
	// QPixmap(int, int, const uchar*, bool)
	x_QPixmap* xret = new x_QPixmap((int)x[1].x_int,(int)x[2].x_int,(const uchar*)x[3].x_voidp,(bool)x[4].x_bool);
	x[0].x_voidp = (void*)xret;
    }
    x_QPixmap(int x1, int x2, const uchar* x3, bool x4) : QPixmap(x1, x2, x3, x4) {
    }
    void x_81(xargs *x) const {
	// metric(int)
	int xret = this->QPixmap::metric((int)x[1].x_int);
	x[0].x_int = (int)xret;
    }
    virtual bool cmd(int x1, QPainter* x2, QPDevCmdParam* x3) {
	xargs x[4];
	x[1].x_int = (int)x1;
	x[2].x_voidp = (void*)x2;
	x[3].x_voidp = (void*)x3;
	if(call_method((void*)this, 5558, x)) return (bool)x[0].x_bool;
	return this->QPaintDevice::cmd(x1, x2, x3);
    }
    virtual void detach() {
	xargs x[1];
	if(call_method((void*)this, 5926, x)) return;
	this->QPixmap::detach();
    }
    virtual int fontInf(QFont* x1, int x2) const {
	xargs x[3];
	x[1].x_voidp = (void*)x1;
	x[2].x_int = (int)x2;
	if(call_method((void*)this, 5563, x)) return (int)x[0].x_int;
	return this->QPaintDevice::fontInf(x1, x2);
    }
    virtual int fontMet(QFont* x1, int x2, const char* x3, int x4) const {
	xargs x[5];
	x[1].x_voidp = (void*)x1;
	x[2].x_int = (int)x2;
	x[3].x_voidp = (void*)x3;
	x[4].x_int = (int)x4;
	if(call_method((void*)this, 5560, x)) return (int)x[0].x_int;
	return this->QPaintDevice::fontMet(x1, x2, x3, x4);
    }
    virtual int metric(int x1) const {
	xargs x[2];
	x[1].x_int = (int)x1;
	if(call_method((void*)this, 5944, x)) return (int)x[0].x_int;
	return this->QPixmap::metric(x1);
    }
    virtual int resolution() const {
	xargs x[1];
	if(call_method((void*)this, 5556, x)) return (int)x[0].x_int;
	return this->QPaintDevice::resolution();
    }
    virtual void setResolution(int x1) {
	xargs x[2];
	x[1].x_int = (int)x1;
	if(call_method((void*)this, 5555, x)) return;
	this->QPaintDevice::setResolution(x1);
    }
    ~x_QPixmap() {}
};
void xcall_QPixmap(xargs *x, void *s, int xi) {
    x_QPixmap *xself = (x_QPixmap*)s;
    switch(xi) {
	case 0: x_QPixmap::x_0(x);	break;
	case 1: x_QPixmap::x_1(x);	break;
	case 2: x_QPixmap::x_2(x);	break;
	case 3: x_QPixmap::x_3(x);	break;
	case 4: x_QPixmap::x_4(x);	break;
	case 5: x_QPixmap::x_5(x);	break;
	case 6: x_QPixmap::x_6(x);	break;
	case 7: x_QPixmap::x_7(x);	break;
	case 8: x_QPixmap::x_8(x);	break;
	case 9: x_QPixmap::x_9(x);	break;
	case 10: x_QPixmap::x_10(x);	break;
	case 11: x_QPixmap::x_11(x);	break;
	case 12: x_QPixmap::x_12(x);	break;
	case 13: x_QPixmap::x_13(x);	break;
	case 14: x_QPixmap::x_14(x);	break;
	case 15: x_QPixmap::x_15(x);	break;
	case 16: x_QPixmap::x_16(x);	break;
	case 17: x_QPixmap::x_17(x);	break;
	case 18: x_QPixmap::x_18(x);	break;
	case 19: x_QPixmap::x_19(x);	break;
	case 20: x_QPixmap::x_20(x);	break;
	case 21: x_QPixmap::x_21(x);	break;
	case 22: x_QPixmap::x_22(x);	break;
	case 23: xself->x_23(x);	break;
	case 24: xself->x_24(x);	break;
	case 25: xself->x_25(x);	break;
	case 26: xself->x_26(x);	break;
	case 27: xself->x_27(x);	break;
	case 28: xself->x_28(x);	break;
	case 29: xself->x_29(x);	break;
	case 30: xself->x_30(x);	break;
	case 31: xself->x_31(x);	break;
	case 32: xself->x_32(x);	break;
	case 33: xself->x_33(x);	break;
	case 34: xself->x_34(x);	break;
	case 35: xself->x_35(x);	break;
	case 36: xself->x_36(x);	break;
	case 37: xself->x_37(x);	break;
	case 38: xself->x_38(x);	break;
	case 39: xself->x_39(x);	break;
	case 40: xself->x_40(x);	break;
	case 41: xself->x_41(x);	break;
	case 42: xself->x_42(x);	break;
	case 43: xself->x_43(x);	break;
	case 44: xself->x_44(x);	break;
	case 45: xself->x_45(x);	break;
	case 46: xself->x_46(x);	break;
	case 47: xself->x_47(x);	break;
	case 48: xself->x_48(x);	break;
	case 49: xself->x_49(x);	break;
	case 50: xself->x_50(x);	break;
	case 51: xself->x_51(x);	break;
	case 52: xself->x_52(x);	break;
	case 53: xself->x_53(x);	break;
	case 54: xself->x_54(x);	break;
	case 55: xself->x_55(x);	break;
	case 56: xself->x_56(x);	break;
	case 57: xself->x_57(x);	break;
	case 58: xself->x_58(x);	break;
	case 59: xself->x_59(x);	break;
	case 60: xself->x_60(x);	break;
	case 61: xself->x_61(x);	break;
	case 62: xself->x_62(x);	break;
	case 63: xself->x_63(x);	break;
	case 64: xself->x_64(x);	break;
	case 65: x_QPixmap::x_65(x);	break;
	case 66: x_QPixmap::x_66(x);	break;
	case 67: x_QPixmap::x_67(x);	break;
	case 68: x_QPixmap::x_68(x);	break;
	case 69: x_QPixmap::x_69(x);	break;
	case 70: x_QPixmap::x_70(x);	break;
	case 71: x_QPixmap::x_71(x);	break;
	case 72: x_QPixmap::x_72(x);	break;
	case 73: x_QPixmap::x_73(x);	break;
	case 74: x_QPixmap::x_74(x);	break;
	case 75: x_QPixmap::x_75(x);	break;
	case 76: x_QPixmap::x_76(x);	break;
	case 77: x_QPixmap::x_77(x);	break;
	case 78: x_QPixmap::x_78(x);	break;
	case 79: x_QPixmap::x_79(x);	break;
	case 80: x_QPixmap::x_80(x);	break;
	case 81: xself->x_81(x);	break;
	case 82: delete (QPixmap*)xself;	break;
    }
}
