<config>
    <moduleName>solid</moduleName>
    <parts>10</parts>
    <parentModules>
        <module>qtcore</module>
    </parentModules>
    <scalarTypes>
        <!-- QString is a class, but represented as a scalar (#) in munged names -->
        <typeName>QString</typeName>
    </scalarTypes>
    <voidpTypes>
        <!-- both are classes, but they are represented as Smoke::t_voidp -->
        <typeName>QStringList</typeName>
        <typeName>QString</typeName>
    </voidpTypes>
    <exclude>
        <!-- private stuff -->
        <signature>.*::d</signature>
        <signature>.*::d_ptr</signature>
        <signature>.*::q_ptr</signature>
        <signature>.*::q</signature>
        <signature>.*QDebug.*</signature>
        <signature>.*Q3.*</signature>

        @BEGIN_BROKEN_EXPORT@
        <signature>.*Solid::Networking::(set)?([dD]is)?[cC]onnectPolicy\(.*\)</signature>
        @END_BROKEN_EXPORT@
    </exclude>
    <functions>
        <!-- everything in that namespace.. -->
        <name>Solid::.*</name>
    </functions>
    <classList>
        <class>Solid</class>
        <class>Solid::AcAdapter</class>
        <class>Solid::AudioInterface</class>
        <class>Solid::Battery</class>
        <class>Solid::Block</class>
        <class>Solid::Button</class>
        <class>Solid::Camera</class>
        <class>Solid::Device</class>
        <class>Solid::DeviceInterface</class>
        <class>Solid::DeviceNotifier</class>
        <class>Solid::DvbInterface</class>
        <class>Solid::GenericInterface</class>
        <class>Solid::Networking</class>
        @BEGIN_BROKEN_EXPORT@
        <class>Solid::Networking::Notifier</class>
        @END_BROKEN_EXPORT@
        <class>Solid::NetworkInterface</class>
        <class>Solid::OpticalDisc</class>
        <class>Solid::OpticalDrive</class>
        <class>Solid::PortableMediaPlayer</class>
        <class>Solid::PowerManagement</class>
        @BEGIN_BROKEN_EXPORT@
        <class>Solid::PowerManagement::Notifier</class>
        @END_BROKEN_EXPORT@
        <class>Solid::Predicate</class>
        <class>Solid::Processor</class>
        <class>Solid::StorageAccess</class>
        <class>Solid::StorageDrive</class>
        <class>Solid::StorageVolume</class>
        <class>Solid::Video</class>
    </classList>
</config>
